### ISSUE TITLE
Running `formatVersionCatalog` inserts an empty bundle block if no bundles are already defined

### ISSUE THREAD

**Issue by WhosNickDoglio** [pemistahl/version-catalog-linter-gradle-plugin#4]
Greetings I just tested this out on my project and noticed if a `bundles` section isn't defined in the Catalog an empty one will be inserted. It would be nice if we could avoid adding this empty bundles section

**Comment by pemistahl** [comment]
Thanks for letting me know. I'm going to fix that.

**Comment by pemistahl** [comment]
Fixed in commit https://github.com/pemistahl/version-catalog-linter-gradle-plugin/commit/3fc77dbbcaaf951a999bfaee45f306a5ecc7e4ce.
